

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
inhibit_all_warnings!
#source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods', :deterministic_uuids => false

#target 'Combo' do inhibit_all_warnings!

target 'Combo' do
  pod 'LookinServer', :configurations => ['Debug']
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.8.0'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.62.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'comboTodayWidget' do 
  
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.8.0'
end
target 'comboUnFinished' do 
  
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.8.0'
end

