# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'Combo' do
#定义dayibase的版本。
pod 'Reveal-iOS-SDK' ,:configurations => ['Debug']
#pod 'GDTMobSDK', '~> 4.8.4' 
end
